# Generated by Django 5.1.4 on 2024-12-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Urmart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shop_id",
            field=models.PositiveIntegerField(
                choices=[(1, "um"), (2, "ms"), (3, "ps")], default=1
            ),
        ),
    ]
