# Generated by Django 5.1.4 on 2024-12-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Urmart', '0002_alter_order_shop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='member_id',
            new_name='member',
        ),
    ]
