# Generated by Django 5.1.4 on 2024-12-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("urmart", "0003_member_is_vip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="is_vip",
        ),
    ]
