# Generated by Django 5.1.4 on 2024-12-28 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urmart", "0005_alter_member_id_alter_order_id_alter_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="member",
            field=models.ForeignKey(
                blank=True,
                help_text="購買成員",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="urmart.member",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                decimal_places=0, default=0, help_text="商品單價", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="購買產品",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="urmart.product",
            ),
        ),
    ]
