# Generated by Django 5.1.4 on 2024-12-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urmart", "0006_alter_order_member_alter_order_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
    ]
