# Generated by Django 5.1.4 on 2025-01-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urmart', '0009_remove_shopsalesstats_date_shopsalesstats_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
    ]
