# Generated by Django 5.1.4 on 2025-01-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urmart', '0010_remove_orderitem_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.ForeignKey(blank=True, help_text='購買成員', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='urmart.member'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, help_text='所屬訂單', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='urmart.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(help_text='訂單中的商品', on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='urmart.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='商品所屬商店', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='urmart.shop'),
        ),
        migrations.AlterField(
            model_name='shopsalesstats',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='所屬商店', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_stats', to='urmart.shop'),
        ),
    ]
